In [1]:
import pandas as pd
import numpy as np
from scipy import spatial
import networkx as nx

In [2]:
df_substations = pd.read_excel('./substations.xlsx', index_col=0)
df_powerplants = pd.read_excel('./plants.xlsx', index_col=0)
df_grid = pd.read_excel('./grid.xlsx', index_col=0)
df_grid = df_grid[df_grid.susceptance != 0]
Grid = nx.from_pandas_edgelist(df_grid, 'substation_1', 'substation_2', edge_attr=["susceptance"])

substation_ids = []
substation_locs = []
for index, row in df_substations.iterrows():
    substation_ids.append(index)
    substation_locs.append((row.lon, row.lat))
    
substation_tree = spatial.KDTree(substation_locs)

for index, row in df_powerplants.iterrows():
    result = substation_tree.query([(row.lon,row.lat)])
    df_powerplants.loc[index, 'node'] = substation_ids[result[1][0]]
    
df_powerplants.node = df_powerplants.node.astype(int)
display(df_powerplants)

,name,eic,type,zone,installed_capacity,lat,lon,node
0,GDK-Mellach,14W-WGM-KW-----J,natural_gas,AT,838.0,46.911700,15.488300,1091
1,Ottensheim-Wilhering,14W-BOW-KW-----9,hydro_run_of_river,AT,179.0,48.316500,14.151057,1280
2,FHKW Linz Mitte,14WLSG-MITTE---U,natural_gas,AT,216.8,48.299219,14.322935,690
3,Kraftwerk Theiß,14W-KW-THE-EVN-7,natural_gas,AT,485.0,48.394861,15.710147,1064
4,FHKW Linz Süd,14WLSG-1SUED---5,natural_gas,AT,158.0,48.267893,14.346898,690
...,...,...,...,...,...,...,...,...
636,Petrokemija Kutina,NaN,natural_gas,HR,35.0,45.471290,16.792320,1171
637,Dubrovnik,NaN,hydro_reservoir,HR,216.0,42.603001,18.235001,187
638,Fuzine,NaN,hydro_pumped_storage,HR,5.7,45.304985,14.714837,412
639,He Rijeka,NaN,hydro_run_of_river,HR,36.8,45.334999,14.452000,417
640,Hidroelektrana Velebit Pump,NaN,hydro_pumped_storage,HR,276.0,44.200733,15.681117,16

In [13]:
K = 5
omega = np.zeros((len(df_powerplants), len(Grid.nodes), K))

nodes_list = list(Grid.nodes)
for p, (p_index, plant) in enumerate(df_powerplants.iterrows()):
    node = plant['node']
    neighbours = list(nx.single_source_shortest_path_length(Grid, node, cutoff=K).keys())[0:K]
    for i, node in enumerate(neighbours):
        n_index = nodes_list.index(node)
        omega[p][n_index][i] = 1
        
with open('omega_matrix.npy', 'wb') as f:
    np.save(f, omega)