In [1]:
import pandas as pd
import networkx as nx
import numpy as np
import requests
import geopandas as gpd
import osmnx as ox

In [17]:
df_grid = pd.read_excel('./grid.xlsx', index_col=0)
df_substations = pd.read_excel('./substations.xlsx', index_col=0)

pd.set_option('display.max_rows', 100)

In [18]:
df_tielines = pd.read_excel('./jao_static_grid.xlsx', sheet_name='Tielines', skiprows=[0])
df_tielines = df_tielines[[
    'NE_name', 'EIC_Code', 'TSO', 
    'Full_name', 'Full_name.1', 'Voltage_level(kV)', 
    'Resistance_R(Ω)', 'Reactance_X(Ω)', 'Susceptance_B(μS)', 'Length_(km)'
]]
df_tielines = df_tielines.rename(columns={
    'NE_name': 'name', 
    'EIC_Code': 'eic',
    'TSO': 'tso',
    'Voltage_level(kV)': 'voltage',
    'Resistance_R(Ω)': 'resistance',
    'Reactance_X(Ω)': 'reactance',
    'Susceptance_B(μS)': 'susceptance',
    'Length_(km)': 'length',
    'Full_name': 'substation_1',
    'Full_name.1': 'substation_2',
})

tso_zone_map = {
    '50HERTZ': 'DE', 
    'Amprion GmbH': 'DE', 
    'APG': 'AT', 
    'CEPS': 'CZ', 
    'Creos': 'DE', 
    'ELES': 'SI', 
    'ELIA': 'BE',
    'HOPS': 'HR', 
    'MAVIR': 'HU', 
    'PSE': 'PL', 
    'RTE': 'FR', 
    'SEPS': 'SK', 
    'TEL': 'RO', 
    'TENNET NL': 'NL',
    'TENNETGMBH': 'DE', 
    'TRANSNETBW': 'DE'
}

df_tielines['zone'] = df_tielines.apply(lambda row : tso_zone_map[row.tso], axis=1)

In [19]:
def get_from_zone(row):
    if row['eic'][3] == '-':
        return row['eic'][4] + row['eic'][5]
    else:
        return row['zone']
    
def get_to_zone(row):
    if row['eic'][3] == '-':
        return row['eic'][7] + row['eic'][8]
    else:
        return row['zone']

df_tielines['from_zone'] = df_tielines.apply(lambda row: get_from_zone(row), axis=1)
df_tielines['to_zone'] = df_tielines.apply(lambda row: get_to_zone(row), axis=1)

z1 = set(df_tielines['from_zone'].unique())
z1 = z1.union(df_tielines['to_zone'].unique())
zones = list(z1)

relevant_zones = ['DE', 'AT', 'CZ', 'DE', 'SI', 'BE', 'HR', 'HU', 'PL', 'FR', 'SK', 'RO', 'NL', 'D2', 'D4', 'D7', 'D8']

df_tielines = df_tielines[(df_tielines['from_zone'].isin(relevant_zones)) & (df_tielines['to_zone'].isin(relevant_zones))]

In [20]:
substations = df_substations.name.tolist()
substations = list(map(str.strip,substations))
tieline_substations = []

for index, row in df_tielines.iterrows():
    if row['substation_1'].strip() not in tieline_substations:
        tieline_substations.append(row['substation_1'])
    if row['substation_2'].strip() not in tieline_substations:
        tieline_substations.append(row['substation_2'])
        
new_substations = set(list(map(str.lower,tieline_substations))).difference(list(map(str.lower,substations)))
exclude_list = [
    'mukachevo', 'zahidno ukrainska', 'vulcanesti', 'prijedor', # non-fbmc zones
    'mt-saint-martin', # FR, add back later
    'sanem', 'sotel', # LU, add back later
    'nemo convertor station', # uk, non-fbmc
    'vill', 'kempten', 'laufenburg', 'oftringen', 'kasso', 'walgau', # DE, add back later
    'laufenburg', 'oftringen', # swiss, non-fbmc
    'liskowiec', # PL add back later
    'kasso', # DK, non-fbmc
]
new_substations = list(filter(lambda x: x not in exclude_list, new_substations))

substation_zones = []
substation_tso = []

for subst in new_substations:
    matches = df_tielines[df_tielines['substation_1'].apply(str.lower) == subst.strip()]
    print(subst.strip())
    substation_zones.append(matches.iloc[0]['zone'])
    substation_tso.append(matches.iloc[0]['tso'])

df_substations_extra = pd.DataFrame(list(zip(new_substations.copy(), substation_zones.copy(), substation_tso.copy())), columns =['name', 'zone', 'tso'])
df_substations_extra['lat'] = None
df_substations_extra['lon'] = None

bürs
cikovce
repiquage bifferdange 220kv
meiningen
walgauwerk
monceau
prijedor

In [21]:
display(df_substations_extra)
df_substations_extra.to_excel("tieline_substations.xlsx")

                          name zone         tso   lat   lon
0                        bürs    DE  TRANSNETBW  None  None
1                      cikovce   SI        ELES  None  None
2  repiquage bifferdange 220kv   BE        ELIA  None  None
3                    meiningen   AT         APG  None  None
4                   walgauwerk   AT         APG  None  None
5                      monceau   BE        ELIA  None  None
6                     prijedor   HR        HOPS  None  None

In [22]:
df_grid = pd.read_excel('./grid.xlsx', index_col=0)
df_substations = pd.read_excel('./substations.xlsx', index_col=0)

non_fbmc_substations = ['mukachevo', 'zahidno ukrainska', 'vulcanesti', 'prijedor', 'nemo convertor station', 'laufenburg', 'oftringen', 'kasso']
df_tielines = df_tielines[~df_tielines['name'].isin(non_fbmc_substations)]

In [ ]:
for index, row in df_tielines.iterrows():
    s1 = df_substations.index[df_substations.name == row.substation_1].tolist()[0]
    s2 = df_substations.index[df_substations.name == row.substation_2].tolist()[0]
    print(s1, ', ', s2)
    #df_tielines.loc[index, 'substation_1'] = s1
    #df_tielines.loc[index, 'substation_2'] = s2