In [2]:
import pandas as pd

In [3]:
df_powerplants = pd.read_csv('./powerplants.csv')

In [4]:
df_pp_uk = df_powerplants[df_powerplants.Country.isin(['United Kingdom'])]
display(df_pp_uk)

,id,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,DateIn,DateRetrofit,DateOut,lat,lon,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,EIC,projectID
54,54,Crua,Hydro,Pumped Storage,Store,United Kingdom,440.0,NaN,1965.0,1965.0,NaN,56.394104,-5.114319,15.909091,0.0,0.0,0.0,{'48WSTN00000CRUAC'},"{'ENTSOE': {'48WSTN00000CRUAC'}, 'OPSD': {'OEU..."
55,55,Dino,Hydro,Run-Of-River,Store,United Kingdom,2016.0,NaN,1984.0,1984.0,NaN,53.118744,-4.113624,5.777778,0.0,0.0,0.0,{'48WSTN10000DINOQ'},"{'ENTSOE': {'48WSTN10000DINOQ'}, 'OPSD': {'OEU..."
56,56,Ffes,Hydro,Run-Of-River,Store,United Kingdom,384.0,NaN,1963.0,1963.0,NaN,52.980785,-3.968708,4.805556,0.0,0.0,0.0,{'48WSTN00000FFESK'},"{'ENTSOE': {'48WSTN00000FFESK'}, 'OPSD': {'OEU..."
57,57,Foye,Hydro,Run-Of-River,Store,United Kingdom,320.0,NaN,1968.0,1974.0,NaN,57.255362,-4.493152,20.655738,0.0,0.0,0.0,{'48WSTN00000FOYEQ'},"{'ENTSOE': {'48WSTN00000FOYEQ'}, 'OPSD': {'OEU..."
58,58,Sloy,Hydro,Run-Of-River,Store,United Kingdom,153.0,NaN,1950.0,1950.0,NaN,56.261512,-4.763588,NaN,0.0,0.0,0.0,{'48WSTN00000SLOY0'},"{'ENTSOE': {'48WSTN00000SLOY0'}, 'OPSD': {'OEU..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3493,3593,Meig Dam,Hydro,NaN,PP,United Kingdom,0.1,NaN,1954.0,1954.0,NaN,57.565006,-4.717085,NaN,0.0,0.0,0.0,{nan},{'OPSD': {'OEU-3033'}}
3532,3659,Pilkington Greengate,Natural Gas,CCGT,PP,United Kingdom,10.0,NaN,1998.0,1998.0,NaN,53.442988,-2.739958,NaN,0.0,0.0,0.0,{nan},{'OPSD': {'OEU-3070'}}
3556,3708,Selset,Hydro,NaN,PP,United Kingdom,0.8,NaN,2010.0,2010.0,NaN,54.585667,-2.124333,NaN,0.0,0.0,0.0,{nan},{'OPSD': {'OEU-2955'}}
3558,3711,Shin Diversion Dam,Hydro,NaN,PP,United Kingdom,0.1,NaN,1958.0,1958.0,NaN,58.012220,-4.402339,NaN,0.0,0.0,0.0,{nan},{'OPSD': {'OEU-3050'}}
3569,3728,Stanley Mill,Hydro,NaN,PP,United Kingdom,0.8,NaN,2003.0,2003.0,NaN,56.479236,-3.437670,NaN,0.0,0.0,0.0,{nan},{'OPSD': {'OEU-2956'}}

In [5]:
df_pp_uk.to_excel('powerplants_uk.xlsx')