In [9]:
from entsoe import EntsoePandasClient
import pandas as pd

client = EntsoePandasClient(api_key="b18dfce9-f1e3-4d07-822f-4abd1438e602")

borders = [
    ['FR', 'CH'],
    ['FR', 'ES'],
    ['FR', 'GB'],
    ['FR', 'IT_NORD'],
    ['AT', 'IT_NORD'],
    ['AT', 'CH'],
    ['BE', 'GB'],
    ['NL', 'DK_1'],
    ['NL', 'GB'],
    ['NL', 'NO_2'],
    ['SI', 'IT_NORD'],
]

start = pd.Timestamp('20220901', tz='Europe/Amsterdam')
end = pd.Timestamp('20230228', tz='Europe/Amsterdam')

In [10]:
df_demand = pd.read_excel("./optimisation/data/demand.xlsx", index_col=0)

In [12]:
df_atc = pd.DataFrame()
#df_atc.index = df_demand.index

for border in borders:
    atc_1 = client.query_net_transfer_capacity_dayahead(border[0], border[1], start=start, end=end)
    atc_2 = client.query_net_transfer_capacity_dayahead(border[1], border[0], start=start, end=end)
    
    atc_1 = atc_1.tz_localize(None)
    atc_2 = atc_2.tz_localize(None)
    
    df_atc[border[0] + '_' + border[1]] = atc_1
    df_atc[border[1] + '_' + border[0]] = atc_2
    
display(df_atc)

,FR_CH,CH_FR,FR_ES,ES_FR,FR_GB,GB_FR,FR_IT_NORD,IT_NORD_FR,AT_IT_NORD,IT_NORD_AT,...,BE_GB,GB_BE,NL_DK_1,DK_1_NL,NL_GB,GB_NL,NL_NO_2,NO_2_NL,SI_IT_NORD,IT_NORD_SI
2022-09-01 00:00:00+02:00,3000.0,1100.0,3098.0,2960.0,3028.0,3028.0,3059.0,1055.0,300.0,100.0,...,1012.0,1012.0,700.0,700.0,1016.0,1016.0,0.0,0.0,577.0,645.0
2022-09-01 01:00:00+02:00,3000.0,1100.0,3098.0,2960.0,3028.0,3028.0,3059.0,1055.0,300.0,100.0,...,1012.0,1012.0,700.0,700.0,1076.0,1076.0,0.0,0.0,577.0,645.0
2022-09-01 02:00:00+02:00,3000.0,1100.0,3098.0,2960.0,3028.0,3028.0,3059.0,1055.0,300.0,100.0,...,1012.0,1012.0,700.0,700.0,1076.0,1076.0,0.0,0.0,577.0,645.0
2022-09-01 03:00:00+02:00,3000.0,1100.0,3098.0,2960.0,3028.0,3028.0,3071.0,1055.0,301.0,100.0,...,1012.0,1012.0,700.0,700.0,1016.0,1016.0,0.0,0.0,580.0,645.0
2022-09-01 04:00:00+02:00,3000.0,1100.0,3098.0,3145.0,3028.0,3028.0,3071.0,1055.0,301.0,100.0,...,1012.0,1012.0,700.0,700.0,1016.0,1016.0,0.0,0.0,580.0,645.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-27 19:00:00+01:00,3700.0,1200.0,2636.0,1800.0,3528.0,3528.0,3451.0,1495.0,298.0,100.0,...,1032.0,1012.0,700.0,700.0,1067.0,1067.0,640.0,640.0,669.0,660.0
2023-02-27 20:00:00+01:00,3700.0,1200.0,2636.0,1800.0,3528.0,3528.0,3451.0,1495.0,298.0,100.0,...,1032.0,1012.0,700.0,700.0,1067.0,1067.0,640.0,640.0,669.0,660.0
2023-02-27 21:00:00+01:00,3700.0,1200.0,2636.0,1800.0,3028.0,3028.0,3254.0,1495.0,286.0,100.0,...,1032.0,1012.0,700.0,700.0,1067.0,1067.0,640.0,640.0,631.0,660.0
2023-02-27 22:00:00+01:00,3700.0,1200.0,2636.0,1800.0,4028.0,4028.0,3254.0,1495.0,286.0,100.0,...,1012.0,1012.0,700.0,700.0,1067.0,1067.0,640.0,640.0,631.0,660.0
2023-02-27 23:00:00+01:00,3700.0,1200.0,2636.0,1800.0,4028.0,4028.0,3079.0,1660.0,265.0,145.0,...,1012.0,1012.0,700.0,700.0,1067.0,1067.0,640.0,640.0,528.0,680.0

In [ ]:
df_atc.to_excel("./optimisation/data/atc.xlsx")