In [49]:
import wapi
import pandas as pd

countries = ['AT', 'BE', 'CZ', 'DE', 'FR', 'HR', 'HU', 'NL', 'PL', 'RO', 'SI', 'SK']

In [2]:
session = wapi.Session(
    client_id='XgLHQRyKUrAgyJm.XAQSZRkpBvJiEnnQ', 
    client_secret='8FpJH3WeVQa8BSGqMYNTSfLH3P25TmtC52Z.Ticuotd2ygYCv8-0tG-e09X0HQzojaz2E2aBd2ydGbW_RjIJ2ItjsmOw2vDclcWH', 
    timeout=300
)

In [50]:
for zone in countries:
    print(zone.lower())

at
be
cz
de_lu
fr
hr
hu
nl
pl
ro
si
sk

In [29]:
for zone in countries:
    curve = session.get_curve(name='pri nl spot ec00 €/mwh cet h f')
    start_date = pd.Timestamp('2023-1-31 08:00')
    ts = curve.get_instance(issue_date=start_date)
    df = ts.to_pandas()
    display(df)

2023-02-01 00:00:00+01:00     31.67
2023-02-01 01:00:00+01:00     24.09
2023-02-01 02:00:00+01:00     18.65
2023-02-01 03:00:00+01:00     20.33
2023-02-01 04:00:00+01:00     35.86
                              ...
2023-02-09 19:00:00+01:00    210.98
2023-02-09 20:00:00+01:00    180.94
2023-02-09 21:00:00+01:00    147.24
2023-02-09 22:00:00+01:00    133.80
2023-02-09 23:00:00+01:00    123.29
Freq: H, Name: pri nl spot ec00 €/mwh cet h f 2023-01-31T08:00:00+01:00, Length: 216, dtype: float64

In [43]:
df_forecast_zone = pd.DataFrame()
curve = session.get_curve(name='pri nl spot ec00 €/mwh cet h f')
start_date = pd.Timestamp('2023-1-31 08:00')
for day in range(2):
    current_date = start_date + pd.offsets.Day(day)
    ts = curve.get_instance(issue_date=current_date)
    df = ts.to_pandas()
    df_forecast_zone = pd.concat([df_forecast_zone, df[0:24]])
    print(current_date)

2023-01-31 08:00:00
2023-02-01 08:00:00

In [48]:
df_forecast_zone = df_forecast_zone.rename(columns={0: "NL"})
display(df_forecast_zone)

                               NL
2023-02-01 00:00:00+01:00   31.67
2023-02-01 01:00:00+01:00   24.09
2023-02-01 02:00:00+01:00   18.65
2023-02-01 03:00:00+01:00   20.33
2023-02-01 04:00:00+01:00   35.86
2023-02-01 05:00:00+01:00   29.56
2023-02-01 06:00:00+01:00   69.39
2023-02-01 07:00:00+01:00   97.61
2023-02-01 08:00:00+01:00  108.57
2023-02-01 09:00:00+01:00  103.74
2023-02-01 10:00:00+01:00   96.08
2023-02-01 11:00:00+01:00   92.48
2023-02-01 12:00:00+01:00   76.56
2023-02-01 13:00:00+01:00   73.15
2023-02-01 14:00:00+01:00   90.65
2023-02-01 15:00:00+01:00   91.42
2023-02-01 16:00:00+01:00  102.26
2023-02-01 17:00:00+01:00  133.00
2023-02-01 18:00:00+01:00  128.47
2023-02-01 19:00:00+01:00  129.42
2023-02-01 20:00:00+01:00  106.14
2023-02-01 21:00:00+01:00   89.69
2023-02-01 22:00:00+01:00   77.07
2023-02-01 23:00:00+01:00   58.98
2023-02-02 00:00:00+01:00   63.15
2023-02-02 01:00:00+01:00   59.65
2023-02-02 02:00:00+01:00   64.21
2023-02-02 03:00:00+01:00   71.16
2023-02-02 04:00:00+01:00   76.64
2023-02-02 05:00:00+01:00   76.43
2023-02-02 06:00:00+01:00  106.81
2023-02-02 07:00:00+01:00  153.08
2023-02-02 08:00:00+01:00  164.42
2023-02-02 09:00:00+01:00  170.01
2023-02-02 10:00:00+01:00  164.59
2023-02-02 11:00:00+01:00  159.14
2023-02-02 12:00:00+01:00  151.91
2023-02-02 13:00:00+01:00  156.05
2023-02-02 14:00:00+01:00  160.23
2023-02-02 15:00:00+01:00  167.20
2023-02-02 16:00:00+01:00  169.76
2023-02-02 17:00:00+01:00  188.99
2023-02-02 18:00:00+01:00  190.29
2023-02-02 19:00:00+01:00  184.35
2023-02-02 20:00:00+01:00  160.95
2023-02-02 21:00:00+01:00  136.64
2023-02-02 22:00:00+01:00  120.94
2023-02-02 23:00:00+01:00  104.53