In [1]:
from entsoe import EntsoePandasClient
import pandas as pd
import matplotlib.pyplot as plt

client = EntsoePandasClient(api_key="b18dfce9-f1e3-4d07-822f-4abd1438e602")

In [2]:
start = pd.Timestamp('20220901', tz='Europe/Amsterdam')
end = pd.Timestamp('20230228', tz='Europe/Amsterdam')

countries = ['AT', 'BE', 'CZ', 'DE_LU', 'FR', 'HR', 'HU', 'NL', 'PL', 'RO', 'SI', 'SK']

In [12]:
df_demand = pd.DataFrame()
for country_code in countries:
    df_da = client.query_load(country_code, start=start, end=end)
    print(country_code)

    df_da = df_da.rename(columns={
        'Actual Load': country_code, 
    })
    
    df_da = df_da.tz_localize(None)
    df_da = df_da.resample("H").agg(["mean"])
    df_da.columns = [country_code]
    
    if df_demand.empty:
        df_demand = df_da.copy()
    else:
        df_demand[country_code] = df_da[country_code]
        
df_demand.to_excel("demand.xlsx")

AT

AttributeError: 'DataFrame' object has no attribute 'indez'

In [11]:
display(df_demand)

,AT,BE,CZ,DE_LU,FR,HR,HU,NL,PL,RO,SI,SK
2023-03-14 00:00:00,6120.75,8689.50,6690.0,51658.50,47797.0,1679.0,4651.50,9834.00,17006.0,NaN,1332.0,2756.0
2023-03-14 01:00:00,5867.00,8348.00,6719.0,48576.00,46569.0,1570.0,4421.75,9378.75,16432.0,5434.75,1281.0,2687.0
2023-03-14 02:00:00,5775.50,7918.00,6612.0,47201.75,45837.0,1501.0,4269.50,9057.75,16096.0,5367.75,1240.0,2683.0
2023-03-14 03:00:00,5723.50,7965.25,6482.0,48572.00,43549.0,1484.0,4217.25,8898.75,16204.0,5291.00,1232.0,2645.0
2023-03-14 04:00:00,5909.25,8218.75,6631.0,49912.50,43204.0,1526.0,4356.75,9005.00,16762.0,5411.00,1268.0,2728.0
2023-03-14 05:00:00,6564.75,8646.25,7166.0,53548.00,45951.0,1675.0,4693.00,9289.75,17476.0,5618.50,1380.0,2891.0
2023-03-14 06:00:00,7592.25,9528.50,8073.0,60205.50,51337.0,1987.0,5241.50,10459.50,19681.0,6109.00,1696.0,3266.0
2023-03-14 07:00:00,8308.75,10196.25,8558.0,64712.50,55435.0,2208.0,5396.25,11367.50,21412.0,6765.75,1827.0,3452.0
2023-03-14 08:00:00,8520.00,10507.75,8636.0,67361.50,57564.0,2259.0,5222.25,12148.00,21985.0,7010.00,1781.0,3485.0
2023-03-14 09:00:00,8475.25,10942.00,8688.0,68424.00,57871.0,2289.0,4899.25,11717.00,21803.0,6991.00,1652.0,3482.0
2023-03-14 10:00:00,8471.75,11049.00,8677.0,69897.00,57418.0,2259.0,4653.25,11015.50,21623.0,6785.00,1702.0,3408.0
2023-03-14 11:00:00,8402.25,11172.50,8724.0,70871.25,57531.0,2289.0,4605.00,10033.25,21948.0,6563.75,1808.0,3471.0
2023-03-14 12:00:00,8112.25,11221.50,8862.0,71361.75,56176.0,2289.0,4610.25,8241.00,22439.0,6450.25,1919.0,3468.0
2023-03-14 13:00:00,8031.00,11409.25,8852.0,69303.25,54059.0,2297.0,4813.25,6801.25,22512.0,6400.75,1908.0,3461.0
2023-03-14 14:00:00,7935.25,10835.00,8583.0,67809.00,54097.0,2234.0,5142.25,6638.25,22165.0,6302.00,1795.0,3440.0
2023-03-14 15:00:00,7916.75,10603.25,8510.0,66889.75,53418.0,2194.0,5314.50,7970.50,22133.0,6327.00,1732.0,NaN
2023-03-14 16:00:00,7970.25,10391.00,8355.0,65848.75,52394.0,2220.0,5445.25,9803.50,22099.0,6424.00,1736.0,3455.0
2023-03-14 17:00:00,8206.75,10603.75,8280.0,66775.25,52522.0,2285.0,5526.50,11610.75,22446.0,6602.75,1734.0,3458.0
2023-03-14 18:00:00,8470.00,10687.00,8518.0,68221.75,56110.0,2423.0,5739.00,12981.75,23278.0,7002.00,1818.0,3511.0
2023-03-14 19:00:00,8218.75,10947.25,8604.0,67309.25,60597.0,2491.0,5711.75,13557.25,23346.0,7412.50,1819.0,3461.0
2023-03-14 20:00:00,7693.75,10613.00,8269.0,62896.50,57829.0,2438.0,5533.75,12952.75,22875.0,7342.75,1748.0,3387.0
2023-03-14 21:00:00,7127.00,9965.25,7869.0,59494.25,54441.0,2361.0,5328.50,12253.50,21239.0,6970.00,1620.0,3158.0
2023-03-14 22:00:00,6907.25,9621.50,7482.0,56347.00,54461.0,2175.0,5071.00,11389.75,19481.0,6376.25,1508.0,2970.0
2023-03-14 23:00:00,6434.00,9658.50,7095.0,52471.00,54446.0,1944.0,4816.00,10744.25,18268.0,5917.25,1365.0,2832.0