In [1]:
import wapi
import pandas as pd

countries = ['AT', 'BE', 'CZ', 'DE', 'FR', 'HR', 'HU', 'NL', 'PL', 'RO', 'SI', 'SK']

ModuleNotFoundError: No module named 'wapi'

In [2]:
session = wapi.Session(
    client_id='XgLHQRyKUrAgyJm.XAQSZRkpBvJiEnnQ', 
    client_secret='8FpJH3WeVQa8BSGqMYNTSfLH3P25TmtC52Z.Ticuotd2ygYCv8-0tG-e09X0HQzojaz2E2aBd2ydGbW_RjIJ2ItjsmOw2vDclcWH', 
    timeout=300
)

NameError: name 'wapi' is not defined

In [54]:
forecast_zone_list = []

for zone in countries:
    print(zone)
    df_forecast_zone = pd.DataFrame()
    curve = session.get_curve(name='pri {0} spot ec00 â‚¬/mwh cet h f'.format(zone.lower()))
    start_date = pd.Timestamp('2023-1-31 08:00')
    for day in range(28):
        current_date = start_date + pd.offsets.Day(day)
        ts = curve.get_instance(issue_date=current_date)
        df = ts.to_pandas()
        df_forecast_zone = pd.concat([df_forecast_zone, df[0:24]])
    forecast_zone_list.append(df_forecast_zone)

AT
BE
CZ
DE
FR
HR
HU
NL
PL
RO
SI
SK

In [64]:
df_forecast = forecast_zone_list[0].copy()
for index, zone in enumerate(countries):
    df_forecast[zone] = forecast_zone_list[index][0]

df_forecast = df_forecast.drop(columns=[0])
df_forecast.index = df_forecast.index.tz_localize(None)
df_forecast.to_excel("./price_forecasts/volue_day_ahead_ec00.xlsx")
display(df_forecast)

,AT,BE,CZ,DE,FR,HR,HU,NL,PL,RO,SI,SK
2023-02-01 00:00:00,93.23,78.93,77.49,31.69,112.99,94.88,93.98,31.67,65.67,94.88,95.34,93.05
2023-02-01 01:00:00,92.93,65.23,76.85,23.59,100.14,76.31,70.89,24.09,57.44,72.02,79.13,68.96
2023-02-01 02:00:00,95.61,56.92,57.12,18.31,91.06,65.84,58.50,18.65,54.04,60.50,69.66,56.68
2023-02-01 03:00:00,93.42,54.49,51.80,20.31,85.18,62.57,55.53,20.33,54.10,57.57,66.37,53.87
2023-02-01 04:00:00,92.04,45.11,63.54,14.92,79.93,86.51,75.89,35.86,61.56,78.21,92.19,71.17
...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-28 19:00:00,204.86,193.87,202.95,199.66,207.62,207.05,208.42,194.74,187.34,208.94,206.31,209.46
2023-02-28 20:00:00,182.71,174.78,181.51,179.67,186.21,183.67,184.11,175.50,174.46,184.38,183.41,184.48
2023-02-28 21:00:00,164.16,163.41,164.02,163.69,164.14,164.49,164.67,163.42,162.11,164.72,164.37,164.82
2023-02-28 22:00:00,155.54,155.53,155.53,155.53,155.55,155.54,155.55,155.52,155.53,155.55,155.55,155.54
2023-02-28 23:00:00,143.81,142.20,143.62,143.45,144.92,143.79,143.73,142.46,143.57,143.74,143.84,143.68